async function renderProducts(){
  const track=document.getElementById("carouselTrack"); if(!track)return;
  try{const data=await apiJSON("/api/products?featured=true");window.SS_PRODUCT_CACHE=data.products||[];await SSWishlist.ready();track.innerHTML=window.SS_PRODUCT_CACHE.map(ssRenderProductCard).join("");await ssAttachProductCardEvents(track);observeNewReveals(track);}catch(e){console.error(e);SSToast.show(e.message,"error");}
}
function setupCarouselArrows(){const track=document.getElementById("carouselTrack"),prev=document.getElementById("prevBtn"),next=document.getElementById("nextBtn");if(!track||!prev||!next)return;prev.addEventListener("click",()=>track.scrollBy({left:-440,behavior:"smooth"}));next.addEventListener("click",()=>track.scrollBy({left:440,behavior:"smooth"}));}
function setupCategoryClicks(){document.querySelectorAll(".category-card").forEach(card=>card.addEventListener("click",()=>location.href=`category.html?cat=${encodeURIComponent(card.dataset.cat||card.dataset.name||"")}`));}
function setupJoinCommunity(){const btn=document.getElementById("joinCommunityBtn");if(!btn)return;btn.addEventListener("click",()=>SSAuth.isLoggedIn()?SSToast.show("Kamu sudah jadi bagian dari komunitas Second Stories! 🍒","success"):SSAuth.openModal());}
function setupNewsletterForm(){const form=document.getElementById("newsletterForm");if(!form)return;form.addEventListener("submit",e=>{e.preventDefault();const email=form.querySelector("input[type=email]")?.value.trim();if(email){SSToast.show(`Terima kasih! Update promo akan dikirim ke ${email}`,"success");form.reset();}});}
function setupSmoothScroll(){document.querySelectorAll('.nav-pill[href^="#"]').forEach(link=>link.addEventListener("click",e=>{const target=document.querySelector(link.getAttribute("href"));if(target){e.preventDefault();target.scrollIntoView({behavior:"smooth",block:"start"});}}));}
function setupBackgroundAnimation(){const layer=document.getElementById("bgAnimation");if(!layer)return;const emojis=["🍒","♡","✿","✦"],dotColors=["","blue","gold"];for(let i=0;i<22;i++){const el=document.createElement("span"),emoji=Math.random()<.55;el.className=emoji?"floaty emoji":`floaty dot ${dotColors[Math.floor(Math.random()*dotColors.length)]}`.trim();if(emoji)el.textContent=emojis[Math.floor(Math.random()*emojis.length)];else{const s=6+Math.random()*10;el.style.width=`${s}px`;el.style.height=`${s}px`;}const d=Math.random()*20;el.style.left=`${Math.random()*100}vw`;el.style.animationDuration=`${16+Math.random()*18}s, ${3+Math.random()*4}s`;el.style.animationDelay=`${d}s, ${d}s`;layer.appendChild(el);}}
function setupScrollReveal(){const els=document.querySelectorAll(".reveal");if(!els.length)return;if(!(IntersectionObserver in window)){els.forEach(e=>e.classList.add("revealed"));return;}const ob=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add("revealed");ob.unobserve(x.target);}}),{threshold:.15,rootMargin:"0px 0px -40px 0px"});els.forEach(e=>ob.observe(e));}
function observeNewReveals(container){if(!(IntersectionObserver in window)||!container)return;const ob=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add("revealed");ob.unobserve(x.target);}}),{threshold:.15});container.querySelectorAll(".reveal").forEach(e=>ob.observe(e));}
function setupMagneticIcons(){document.querySelectorAll(".category-card").forEach(card=>{const icon=card.querySelector(".cat-icon-frame");if(!icon)return;card.addEventListener("mousemove",e=>{const r=card.getBoundingClientRect();icon.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.25}px, ${(e.clientY-r.top-r.height/2)*.25}px)`});card.addEventListener("mouseleave",()=>icon.style.transform="translate(0,0)" )});}
document.addEventListener("DOMContentLoaded",async()=>{await renderProducts();setupCarouselArrows();setupCategoryClicks();setupJoinCommunity();setupNewsletterForm();setupSmoothScroll();setupBackgroundAnimation();setupScrollReveal();setupMagneticIcons();});
